#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelManageSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hotelManage")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertEmployeeinformation(Employeeinformation instance);
    partial void UpdateEmployeeinformation(Employeeinformation instance);
    partial void DeleteEmployeeinformation(Employeeinformation instance);
    partial void InsertPassword(Password instance);
    partial void UpdatePassword(Password instance);
    partial void DeletePassword(Password instance);
    partial void InsertcustomerManage(customerManage instance);
    partial void UpdatecustomerManage(customerManage instance);
    partial void DeletecustomerManage(customerManage instance);
    partial void InsertSalary(Salary instance);
    partial void UpdateSalary(Salary instance);
    partial void DeleteSalary(Salary instance);
    partial void InsertreserveManage(reserveManage instance);
    partial void UpdatereserveManage(reserveManage instance);
    partial void DeletereserveManage(reserveManage instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::hotelManageSystem.Properties.Settings.Default.hotelManageConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product> Product
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Employeeinformation> Employeeinformation
		{
			get
			{
				return this.GetTable<Employeeinformation>();
			}
		}
		
		public System.Data.Linq.Table<Password> Password
		{
			get
			{
				return this.GetTable<Password>();
			}
		}
		
		public System.Data.Linq.Table<customerManage> customerManage
		{
			get
			{
				return this.GetTable<customerManage>();
			}
		}
		
		public System.Data.Linq.Table<Salary> Salary
		{
			get
			{
				return this.GetTable<Salary>();
			}
		}
		
		public System.Data.Linq.Table<reserveManage> reserveManage
		{
			get
			{
				return this.GetTable<reserveManage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pro_id;
		
		private string _pro_name;
		
		private string _pro_handle;
		
		private string _pro_units;
		
		private double _pro_price;
		
		private double _pro_count;
		
		private System.DateTime _pro_time;
		
		private double _pro_pay;
		
		private double _pro_realpay;
		
		private double _pro_difference;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(string value);
    partial void Onpro_idChanged();
    partial void Onpro_nameChanging(string value);
    partial void Onpro_nameChanged();
    partial void Onpro_handleChanging(string value);
    partial void Onpro_handleChanged();
    partial void Onpro_unitsChanging(string value);
    partial void Onpro_unitsChanged();
    partial void Onpro_priceChanging(double value);
    partial void Onpro_priceChanged();
    partial void Onpro_countChanging(double value);
    partial void Onpro_countChanged();
    partial void Onpro_timeChanging(System.DateTime value);
    partial void Onpro_timeChanged();
    partial void Onpro_payChanging(double value);
    partial void Onpro_payChanged();
    partial void Onpro_realpayChanging(double value);
    partial void Onpro_realpayChanged();
    partial void Onpro_differenceChanging(double value);
    partial void Onpro_differenceChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string pro_name
		{
			get
			{
				return this._pro_name;
			}
			set
			{
				if ((this._pro_name != value))
				{
					this.Onpro_nameChanging(value);
					this.SendPropertyChanging();
					this._pro_name = value;
					this.SendPropertyChanged("pro_name");
					this.Onpro_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_handle", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string pro_handle
		{
			get
			{
				return this._pro_handle;
			}
			set
			{
				if ((this._pro_handle != value))
				{
					this.Onpro_handleChanging(value);
					this.SendPropertyChanging();
					this._pro_handle = value;
					this.SendPropertyChanged("pro_handle");
					this.Onpro_handleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_units", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string pro_units
		{
			get
			{
				return this._pro_units;
			}
			set
			{
				if ((this._pro_units != value))
				{
					this.Onpro_unitsChanging(value);
					this.SendPropertyChanging();
					this._pro_units = value;
					this.SendPropertyChanged("pro_units");
					this.Onpro_unitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_price", DbType="Float NOT NULL")]
		public double pro_price
		{
			get
			{
				return this._pro_price;
			}
			set
			{
				if ((this._pro_price != value))
				{
					this.Onpro_priceChanging(value);
					this.SendPropertyChanging();
					this._pro_price = value;
					this.SendPropertyChanged("pro_price");
					this.Onpro_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_count", DbType="Float NOT NULL")]
		public double pro_count
		{
			get
			{
				return this._pro_count;
			}
			set
			{
				if ((this._pro_count != value))
				{
					this.Onpro_countChanging(value);
					this.SendPropertyChanging();
					this._pro_count = value;
					this.SendPropertyChanged("pro_count");
					this.Onpro_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_time", DbType="DateTime NOT NULL")]
		public System.DateTime pro_time
		{
			get
			{
				return this._pro_time;
			}
			set
			{
				if ((this._pro_time != value))
				{
					this.Onpro_timeChanging(value);
					this.SendPropertyChanging();
					this._pro_time = value;
					this.SendPropertyChanged("pro_time");
					this.Onpro_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_pay", DbType="Float NOT NULL")]
		public double pro_pay
		{
			get
			{
				return this._pro_pay;
			}
			set
			{
				if ((this._pro_pay != value))
				{
					this.Onpro_payChanging(value);
					this.SendPropertyChanging();
					this._pro_pay = value;
					this.SendPropertyChanged("pro_pay");
					this.Onpro_payChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_realpay", DbType="Float NOT NULL")]
		public double pro_realpay
		{
			get
			{
				return this._pro_realpay;
			}
			set
			{
				if ((this._pro_realpay != value))
				{
					this.Onpro_realpayChanging(value);
					this.SendPropertyChanging();
					this._pro_realpay = value;
					this.SendPropertyChanged("pro_realpay");
					this.Onpro_realpayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_difference", DbType="Float NOT NULL")]
		public double pro_difference
		{
			get
			{
				return this._pro_difference;
			}
			set
			{
				if ((this._pro_difference != value))
				{
					this.Onpro_differenceChanging(value);
					this.SendPropertyChanging();
					this._pro_difference = value;
					this.SendPropertyChanged("pro_difference");
					this.Onpro_differenceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employeeinformation")]
	public partial class Employeeinformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _emp_id;
		
		private string _emp_name;
		
		private string _emp_sex;
		
		private string _emp_phone;
		
		private int _emp_age;
		
		private string _emp_position;
		
		private string _emp_address;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_idChanging(string value);
    partial void Onemp_idChanged();
    partial void Onemp_nameChanging(string value);
    partial void Onemp_nameChanged();
    partial void Onemp_sexChanging(string value);
    partial void Onemp_sexChanged();
    partial void Onemp_phoneChanging(string value);
    partial void Onemp_phoneChanged();
    partial void Onemp_ageChanging(int value);
    partial void Onemp_ageChanged();
    partial void Onemp_positionChanging(string value);
    partial void Onemp_positionChanged();
    partial void Onemp_addressChanging(string value);
    partial void Onemp_addressChanged();
    #endregion
		
		public Employeeinformation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string emp_name
		{
			get
			{
				return this._emp_name;
			}
			set
			{
				if ((this._emp_name != value))
				{
					this.Onemp_nameChanging(value);
					this.SendPropertyChanging();
					this._emp_name = value;
					this.SendPropertyChanged("emp_name");
					this.Onemp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_sex", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string emp_sex
		{
			get
			{
				return this._emp_sex;
			}
			set
			{
				if ((this._emp_sex != value))
				{
					this.Onemp_sexChanging(value);
					this.SendPropertyChanging();
					this._emp_sex = value;
					this.SendPropertyChanged("emp_sex");
					this.Onemp_sexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_phone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string emp_phone
		{
			get
			{
				return this._emp_phone;
			}
			set
			{
				if ((this._emp_phone != value))
				{
					this.Onemp_phoneChanging(value);
					this.SendPropertyChanging();
					this._emp_phone = value;
					this.SendPropertyChanged("emp_phone");
					this.Onemp_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_age", DbType="Int NOT NULL")]
		public int emp_age
		{
			get
			{
				return this._emp_age;
			}
			set
			{
				if ((this._emp_age != value))
				{
					this.Onemp_ageChanging(value);
					this.SendPropertyChanging();
					this._emp_age = value;
					this.SendPropertyChanged("emp_age");
					this.Onemp_ageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_position", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string emp_position
		{
			get
			{
				return this._emp_position;
			}
			set
			{
				if ((this._emp_position != value))
				{
					this.Onemp_positionChanging(value);
					this.SendPropertyChanging();
					this._emp_position = value;
					this.SendPropertyChanged("emp_position");
					this.Onemp_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_address", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string emp_address
		{
			get
			{
				return this._emp_address;
			}
			set
			{
				if ((this._emp_address != value))
				{
					this.Onemp_addressChanging(value);
					this.SendPropertyChanging();
					this._emp_address = value;
					this.SendPropertyChanged("emp_address");
					this.Onemp_addressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.password")]
	public partial class Password : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _emp_id;
		
		private string _emp_originalpassword;
		
		private string _emp_updatepassword;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_idChanging(string value);
    partial void Onemp_idChanged();
    partial void Onemp_originalpasswordChanging(string value);
    partial void Onemp_originalpasswordChanged();
    partial void Onemp_updatepasswordChanging(string value);
    partial void Onemp_updatepasswordChanged();
    #endregion
		
		public Password()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_originalpassword", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string emp_originalpassword
		{
			get
			{
				return this._emp_originalpassword;
			}
			set
			{
				if ((this._emp_originalpassword != value))
				{
					this.Onemp_originalpasswordChanging(value);
					this.SendPropertyChanging();
					this._emp_originalpassword = value;
					this.SendPropertyChanged("emp_originalpassword");
					this.Onemp_originalpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_updatepassword", DbType="VarChar(30)")]
		public string emp_updatepassword
		{
			get
			{
				return this._emp_updatepassword;
			}
			set
			{
				if ((this._emp_updatepassword != value))
				{
					this.Onemp_updatepasswordChanging(value);
					this.SendPropertyChanging();
					this._emp_updatepassword = value;
					this.SendPropertyChanged("emp_updatepassword");
					this.Onemp_updatepasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customerManage")]
	public partial class customerManage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cus_name;
		
		private string _cus_phone;
		
		private string _cus_id;
		
		private string _cus_type;
		
		private int _cus_roomid;
		
		private System.DateTime _cus_time;
		
		private int _cus_days;
		
		private double _cus_pay;
		
		private int _cus_extra;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncus_nameChanging(string value);
    partial void Oncus_nameChanged();
    partial void Oncus_phoneChanging(string value);
    partial void Oncus_phoneChanged();
    partial void Oncus_idChanging(string value);
    partial void Oncus_idChanged();
    partial void Oncus_typeChanging(string value);
    partial void Oncus_typeChanged();
    partial void Oncus_roomidChanging(int value);
    partial void Oncus_roomidChanged();
    partial void Oncus_timeChanging(System.DateTime value);
    partial void Oncus_timeChanged();
    partial void Oncus_daysChanging(int value);
    partial void Oncus_daysChanged();
    partial void Oncus_payChanging(double value);
    partial void Oncus_payChanged();
    partial void Oncus_extraChanging(int value);
    partial void Oncus_extraChanged();
    #endregion
		
		public customerManage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_name", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cus_name
		{
			get
			{
				return this._cus_name;
			}
			set
			{
				if ((this._cus_name != value))
				{
					this.Oncus_nameChanging(value);
					this.SendPropertyChanging();
					this._cus_name = value;
					this.SendPropertyChanged("cus_name");
					this.Oncus_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_phone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cus_phone
		{
			get
			{
				return this._cus_phone;
			}
			set
			{
				if ((this._cus_phone != value))
				{
					this.Oncus_phoneChanging(value);
					this.SendPropertyChanging();
					this._cus_phone = value;
					this.SendPropertyChanged("cus_phone");
					this.Oncus_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_id", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cus_id
		{
			get
			{
				return this._cus_id;
			}
			set
			{
				if ((this._cus_id != value))
				{
					this.Oncus_idChanging(value);
					this.SendPropertyChanging();
					this._cus_id = value;
					this.SendPropertyChanged("cus_id");
					this.Oncus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_type", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string cus_type
		{
			get
			{
				return this._cus_type;
			}
			set
			{
				if ((this._cus_type != value))
				{
					this.Oncus_typeChanging(value);
					this.SendPropertyChanging();
					this._cus_type = value;
					this.SendPropertyChanged("cus_type");
					this.Oncus_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_roomid", DbType="Int NOT NULL")]
		public int cus_roomid
		{
			get
			{
				return this._cus_roomid;
			}
			set
			{
				if ((this._cus_roomid != value))
				{
					this.Oncus_roomidChanging(value);
					this.SendPropertyChanging();
					this._cus_roomid = value;
					this.SendPropertyChanged("cus_roomid");
					this.Oncus_roomidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_time", DbType="DateTime NOT NULL")]
		public System.DateTime cus_time
		{
			get
			{
				return this._cus_time;
			}
			set
			{
				if ((this._cus_time != value))
				{
					this.Oncus_timeChanging(value);
					this.SendPropertyChanging();
					this._cus_time = value;
					this.SendPropertyChanged("cus_time");
					this.Oncus_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_days", DbType="Int NOT NULL")]
		public int cus_days
		{
			get
			{
				return this._cus_days;
			}
			set
			{
				if ((this._cus_days != value))
				{
					this.Oncus_daysChanging(value);
					this.SendPropertyChanging();
					this._cus_days = value;
					this.SendPropertyChanged("cus_days");
					this.Oncus_daysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_pay", DbType="Float NOT NULL")]
		public double cus_pay
		{
			get
			{
				return this._cus_pay;
			}
			set
			{
				if ((this._cus_pay != value))
				{
					this.Oncus_payChanging(value);
					this.SendPropertyChanging();
					this._cus_pay = value;
					this.SendPropertyChanged("cus_pay");
					this.Oncus_payChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus_extra", DbType="Int NOT NULL")]
		public int cus_extra
		{
			get
			{
				return this._cus_extra;
			}
			set
			{
				if ((this._cus_extra != value))
				{
					this.Oncus_extraChanging(value);
					this.SendPropertyChanging();
					this._cus_extra = value;
					this.SendPropertyChanged("cus_extra");
					this.Oncus_extraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.salary")]
	public partial class Salary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _emp_id;
		
		private string _emp_name;
		
		private double _basesalary;
		
		private System.Nullable<double> _overwork;
		
		private System.Nullable<double> _extra;
		
		private string _remark;
		
		private System.Nullable<double> _allsalary;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_idChanging(string value);
    partial void Onemp_idChanged();
    partial void Onemp_nameChanging(string value);
    partial void Onemp_nameChanged();
    partial void OnbasesalaryChanging(double value);
    partial void OnbasesalaryChanged();
    partial void OnoverworkChanging(System.Nullable<double> value);
    partial void OnoverworkChanged();
    partial void OnextraChanging(System.Nullable<double> value);
    partial void OnextraChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnallsalaryChanging(System.Nullable<double> value);
    partial void OnallsalaryChanged();
    #endregion
		
		public Salary()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string emp_name
		{
			get
			{
				return this._emp_name;
			}
			set
			{
				if ((this._emp_name != value))
				{
					this.Onemp_nameChanging(value);
					this.SendPropertyChanging();
					this._emp_name = value;
					this.SendPropertyChanged("emp_name");
					this.Onemp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basesalary", DbType="Float NOT NULL")]
		public double basesalary
		{
			get
			{
				return this._basesalary;
			}
			set
			{
				if ((this._basesalary != value))
				{
					this.OnbasesalaryChanging(value);
					this.SendPropertyChanging();
					this._basesalary = value;
					this.SendPropertyChanged("basesalary");
					this.OnbasesalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overwork", DbType="Float")]
		public System.Nullable<double> overwork
		{
			get
			{
				return this._overwork;
			}
			set
			{
				if ((this._overwork != value))
				{
					this.OnoverworkChanging(value);
					this.SendPropertyChanging();
					this._overwork = value;
					this.SendPropertyChanged("overwork");
					this.OnoverworkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extra", DbType="Float")]
		public System.Nullable<double> extra
		{
			get
			{
				return this._extra;
			}
			set
			{
				if ((this._extra != value))
				{
					this.OnextraChanging(value);
					this.SendPropertyChanging();
					this._extra = value;
					this.SendPropertyChanged("extra");
					this.OnextraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="VarChar(50)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allsalary", DbType="Float")]
		public System.Nullable<double> allsalary
		{
			get
			{
				return this._allsalary;
			}
			set
			{
				if ((this._allsalary != value))
				{
					this.OnallsalaryChanging(value);
					this.SendPropertyChanging();
					this._allsalary = value;
					this.SendPropertyChanged("allsalary");
					this.OnallsalaryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reserveManage")]
	public partial class reserveManage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cus2_name;
		
		private string _cus2_phone;
		
		private string _cus2_id;
		
		private string _cus2_type;
		
		private int _cus2_roomid;
		
		private System.DateTime _cus2_time;
		
		private int _cus2_days;
		
		private double _cus2_pay;
		
		private int _cus2_extra;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncus2_nameChanging(string value);
    partial void Oncus2_nameChanged();
    partial void Oncus2_phoneChanging(string value);
    partial void Oncus2_phoneChanged();
    partial void Oncus2_idChanging(string value);
    partial void Oncus2_idChanged();
    partial void Oncus2_typeChanging(string value);
    partial void Oncus2_typeChanged();
    partial void Oncus2_roomidChanging(int value);
    partial void Oncus2_roomidChanged();
    partial void Oncus2_timeChanging(System.DateTime value);
    partial void Oncus2_timeChanged();
    partial void Oncus2_daysChanging(int value);
    partial void Oncus2_daysChanged();
    partial void Oncus2_payChanging(double value);
    partial void Oncus2_payChanged();
    partial void Oncus2_extraChanging(int value);
    partial void Oncus2_extraChanged();
    #endregion
		
		public reserveManage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus2_name", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cus2_name
		{
			get
			{
				return this._cus2_name;
			}
			set
			{
				if ((this._cus2_name != value))
				{
					this.Oncus2_nameChanging(value);
					this.SendPropertyChanging();
					this._cus2_name = value;
					this.SendPropertyChanged("cus2_name");
					this.Oncus2_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus2_phone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cus2_phone
		{
			get
			{
				return this._cus2_phone;
			}
			set
			{
				if ((this._cus2_phone != value))
				{
					this.Oncus2_phoneChanging(value);
					this.SendPropertyChanging();
					this._cus2_phone = value;
					this.SendPropertyChanged("cus2_phone");
					this.Oncus2_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus2_id", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cus2_id
		{
			get
			{
				return this._cus2_id;
			}
			set
			{
				if ((this._cus2_id != value))
				{
					this.Oncus2_idChanging(value);
					this.SendPropertyChanging();
					this._cus2_id = value;
					this.SendPropertyChanged("cus2_id");
					this.Oncus2_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus2_type", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string cus2_type
		{
			get
			{
				return this._cus2_type;
			}
			set
			{
				if ((this._cus2_type != value))
				{
					this.Oncus2_typeChanging(value);
					this.SendPropertyChanging();
					this._cus2_type = value;
					this.SendPropertyChanged("cus2_type");
					this.Oncus2_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus2_roomid", DbType="Int NOT NULL")]
		public int cus2_roomid
		{
			get
			{
				return this._cus2_roomid;
			}
			set
			{
				if ((this._cus2_roomid != value))
				{
					this.Oncus2_roomidChanging(value);
					this.SendPropertyChanging();
					this._cus2_roomid = value;
					this.SendPropertyChanged("cus2_roomid");
					this.Oncus2_roomidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus2_time", DbType="DateTime NOT NULL")]
		public System.DateTime cus2_time
		{
			get
			{
				return this._cus2_time;
			}
			set
			{
				if ((this._cus2_time != value))
				{
					this.Oncus2_timeChanging(value);
					this.SendPropertyChanging();
					this._cus2_time = value;
					this.SendPropertyChanged("cus2_time");
					this.Oncus2_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus2_days", DbType="Int NOT NULL")]
		public int cus2_days
		{
			get
			{
				return this._cus2_days;
			}
			set
			{
				if ((this._cus2_days != value))
				{
					this.Oncus2_daysChanging(value);
					this.SendPropertyChanging();
					this._cus2_days = value;
					this.SendPropertyChanged("cus2_days");
					this.Oncus2_daysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus2_pay", DbType="Float NOT NULL")]
		public double cus2_pay
		{
			get
			{
				return this._cus2_pay;
			}
			set
			{
				if ((this._cus2_pay != value))
				{
					this.Oncus2_payChanging(value);
					this.SendPropertyChanging();
					this._cus2_pay = value;
					this.SendPropertyChanged("cus2_pay");
					this.Oncus2_payChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cus2_extra", DbType="Int NOT NULL")]
		public int cus2_extra
		{
			get
			{
				return this._cus2_extra;
			}
			set
			{
				if ((this._cus2_extra != value))
				{
					this.Oncus2_extraChanging(value);
					this.SendPropertyChanging();
					this._cus2_extra = value;
					this.SendPropertyChanged("cus2_extra");
					this.Oncus2_extraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
